apiVersion: v1
kind: Service
metadata:
  labels:
    app: name-service
  name: name-service
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8050
  selector:
    app: name-service