apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-service
  name: hello-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-service
  template:
    metadata:
      labels:
        app: hello-service
    spec:
      containers:
      - name: hello-service
        image: gcr.io/spring-boot-maven-test/hello-service:latest
        env:
        - name: NAME_SERVICE_URL
          value: "http://35.201.14.21:32223"
        ports:
        - name: http
          containerPort: 8051
        imagePullPolicy: Always