apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-service
  name: hello-service
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 8051
  selector:
    app: hello-service